name: Run yt.sh Runner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Make liveyt.sh executable
        run: chmod +x liveyt.sh
        
      - name: Run liveyt.sh in background
        run: |
          nohup ./liveyt.sh > liveyt.log 2>&1 &
          echo $! > liveyt.pid
          
      - name: Monitor process
        run: |
          while [ -f liveyt.pid ] && ps -p $(cat liveyt.pid) > /dev/null; do
            sleep 300
            echo "[$(date)] Process still running (PID: $(cat liveyt.pid))"
          done
          echo "[$(date)] Process stopped"
